from tkinter import *
window = Tk()
window.title("Facebook log.in page")
window.config(bg="white")
window.iconbitmap("C:\photos\DCIM\Important documents\facebook_icon.ico")  # Replace with your file name
# Continue with your GUI setup...
label = Label(window, text="Facebook", font=("Arial", 40, "bold"), fg="blue", bg="white")
label.place(x=130, y=130)
window.geometry("600x700")
def i():
    text1=("Enter Correct username or password \n"+entry.get()+" is not correct username \n"+"OR\n"+entry1.get()+" is not correct password")
    label3.config(text=text1)
label = Label(window,text = "Facebook",font=("klavika bold",40),fg="blue",bg="white")
label.place(x=130,y=70)
label1=Label(window,text = "Username",bg="white")
label1.place(x=150,y=170)
entry = Entry(window, width=50)
entry.place(x=150, y=190)
label2=Label(window,text = "Password",bg="white")
label2.place(x=150,y=225)
entry1 = Entry(window,width=50)
entry1.place(x=150,y=250)
bt=Button(window,text="Log In",bg="blue",font=("Arial",17),fg="white",command=i)
bt.place(x=150,y=290)
label3=Label(window,text = "",bg="white")
label3.place(x=300,y=400)
label4=Label(window,text = "Forgot Password",bg="white",fg="blue")
label4.place(x=250,y=350)
window.mainloop()